### ISSUE TITLE
Generate stop for every platform

### ISSUE THREAD

**Issue by brechtvdv** [iRail/brail2gtfs#15]
Use identifier of parent station and add # + number of platform

e.g. Platform 1 of  Ghent-Sint-Pieters
stops:008892007#1

**Comment by brechtvdv** [comment]
Using ':' between stationnr and platform would be a better option? E.g.:  stops:008892007:1 @pietercolpaert

**Comment by brechtvdv** [comment]
I used https://irail.be/stations/NMBS to get the amount of platforms, but sometimes it doesn't give results, so the platforms are not added. 
I believe that scraping the stations from the NMBS website directly is better.

**Comment by pietercolpaert** [comment]
I agree... Also, sometimes platforms are letters... So there's no such thing as using "platform 11" → thus 11 platforms ;)

**Comment by brechtvdv** [comment]
Yeah, letters are already checked on :)
