### ISSUE TITLE
Use irail/stations

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/brail2gtfs#46]
For the station resolving, start using irail/stations package on packagist :)

**Comment by brechtvdv** [comment]
:+1:

**Comment by Tjoosten** [comment]
@pietercolpaert I'm working on this right now.

@brechtvdv Can u sync the master and dev branch?

**Comment by brechtvdv** [comment]
@Tjoosten Done

**Comment by Tjoosten** [comment]
Alright. Thx Today or tomoorow you get a pr for the implementation of irail/stations

**Comment by pietercolpaert** [comment]
@Tjoosten the same issue has to be fixed, but in this repo: https://github.com/iRail/hyperRail/issues/123

I think it's better to focus on that one as it's easier to test right now

**Comment by Tjoosten** [comment]
Alright.

**Comment by pietercolpaert** [comment]
Fixed in https://github.com/iRail/brail2gtfs/commit/d0fa0e59e74757f848dd57ab16b3aa8f7163d61c
