### ISSUE TITLE
PHPunit

### ISSUE THREAD

**Issue by Tjoosten** [iRail/brail2gtfs#49]
Hi @brechtvdv Can u write php unit tests for this repo. If you write the tests. I can maybe change the curl to guzzle and implement iRail/stations

**Comment by brechtvdv** [comment]
Yeah, will do that later. Guzzle didn't return the expected HTML and curl works so I wouldn't put energy in changing that :) The stations would be great! Btw please do next PR to development branch :)

**Comment by Tjoosten** [comment]
Alright. But i'm waiting till the php unit tests. The current test method throwing errors.

**Comment by pietercolpaert** [comment]
Couple of unit tests added: closing this issue.
