### ISSUE TITLE
Throwed error.

### ISSUE THREAD

**Issue by Tjoosten** [iRail/brail2gtfs#55]
<img width="720" alt="schermafbeelding 2015-09-10 om 23 39 24" src="https://cloud.githubusercontent.com/assets/5157609/9801738/3c622eb6-5815-11e5-9b14-c580061c6f1b.png">

**NOTE: I will make a bugfix for this. maybe @brechtvdv can assign me?**

**Comment by brechtvdv** [comment]
It only works now when you're in the root directory of the project and run `php scripts/1-stops.txt.php`. It would be nice if you made a fix for all the scripts that makes filepaths relative to the location of the script.

**Comment by brechtvdv** [comment]
@pietercolpaert Can you make a @Tjoosten team and add this repo, so I can assign him?

**Comment by pietercolpaert** [comment]
The scripts should be ran from the root of the directory of the repository as indicated by the README.md
