### ISSUE TITLE
Changing step 2 into generating a routes.tmp

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/brail2gtfs#7]
In step 2, I wouldn't just yet populate **routes.txt**. I would do that in step 3, while populating **trips.txt** **calendar_dates.txt** and **calendar.txt**.

Instead, I want another CSV file to be collected. This CSV file should have this header:

``` csv
route_short_name,date
```
- `route_short_names` (e.g., "P8008")
- date in iso8601 (without time)

For each day we're scraping, it should list the all the `route_short_names` (e.g., "P8008") that operate that day.
## Post-processing

Post processing that file should sort the file by `route_short_name`. This way, when reading it in step 3.trips.txt.php, it will be able to figure out which request to do with what time set

**Comment by brechtvdv** [comment]
Zip: https://drive.google.com/open?id=0B6YfG1-sBx6UaXlNb0p2RjJwZjA&authuser=0
